apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: short-app-postgres-pvc
spec:
  # storageClass: 
  resources:
    requests:
      storage: 200Mi
  # volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
